ENABLE_QUANTOP_CONV=1
ENABLE_QUANTGRAD_CONV=1 

ENABLE_QUANTOP_LSTM=0
ENABLE_QUANTGRAD_LSTM=0 
ENABLE_QUANTOP_LSTM_GATES=0
ENABLE_QUANTGRAD_LSTM_GATES=0 

# DFP_INT=0, DFP_UINT=1, TERNARY=2, BLOCK_FP=3, LOWP_FP=4
QUANTEMU_OUTPUT_TYPE=0 

QUANTEMU_PRECISION_ACTS=8
QUANTEMU_PRECISION_FILTER=8
QUANTEMU_PRECISION_GRAD=8 
QUANTEMU_EXPBITS=5          # only used by LOWP_FP, BLOCK_FP types 

# NOBLOCK=0, BLOCK_C=1, BLOCK_CHW=2 
QUANTEMU_CBLOCK_TYPE_ACTS=0
QUANTEMU_CBLOCK_TYPE_FILTER=0

QUANTEMU_CBLOCK_SIZE_ACTS=4096 
QUANTEMU_CBLOCK_SIZE_FILTER=4096 

QUANTEMU_RMODE_ACTS=0
QUANTEMU_RMODE_FILTER=0


export ENABLE_QUANTOP_CONV 
export ENABLE_QUANTGRAD_CONV
export ENABLE_QUANTOP_LSTM 
export ENABLE_QUANTGRAD_LSTM
export ENABLE_QUANTOP_LSTM_GATES
export ENABLE_QUANTGRAD_LSTM_GATES

export QUANTEMU_OUTPUT_TYPE 
export QUANTEMU_PRECISION_ACTS
export QUANTEMU_PRECISION_FILTER
export QUANTEMU_EXPBITS 
export QUANTEMU_PRECISION_GRAD
export QUANTEMU_CBLOCK_TYPE_ACTS
export QUANTEMU_CBLOCK_SIZE_ACTS 
export QUANTEMU_RMODE_ACTS
export QUANTEMU_CBLOCK_TYPE_FILTER
export QUANTEMU_CBLOCK_SIZE_FILTER
export QUANTEMU_RMODE_FILTER
