ENABLE_QUANTOP=False
ENABLE_QUANTGRAD=False 

QUANTEMU_METHOD=4 
QUANTEMU_MBITS_INPUT=8
QUANTEMU_MBITS_KERNEL=8

QUANTEMU_EXPBITS=8 
QUANTEMU_MBITS_GRAD=23 
QUANTEMU_INPUT_BLOCK_TYPE=0
QUANTEMU_INPUT_BLOCK_SIZE=0 
QUANTEMU_INPUT_RMODE=0

QUANTEMU_KERNEL_BLOCK_TYPE=0
QUANTEMU_KERNEL_BLOCK_SIZE=0 
QUANTEMU_KERNEL_RMODE=0


export ENABLE_QUANTOP 
export ENABLE_QUANTGRAD 
export QUANTEMU_METHOD 
export QUANTEMU_MBITS_INPUT
export QUANTEMU_MBITS_KERNEL
export QUANTEMU_EXPBITS 
export QUANTEMU_MBITS_GRAD 
export QUANTEMU_INPUT_BLOCK_TYPE
export QUANTEMU_INPUT_BLOCK_SIZE 
export QUANTEMU_INPUT_RMODE
export QUANTEMU_KERNEL_BLOCK_TYPE
export QUANTEMU_KERNEL_BLOCK_SIZE 
export QUANTEMU_KERNEL_RMODE
